[project]
name = "image-coords-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.3.0",
    "pyinstaller>=6.14.2",
    "sqlmodel>=0.0.8",
    "sqlalchemy>=1.4.0",
    "ttkbootstrap>=1.10.1",
]
